mongo:
  image: mongo
  volumes:
    - mongodata:/data/db
  ports:
    - "27017:27017"
redis:
  image: redis
  volumes:
    - ./data/redis:/data
  ports:
    - "6379:6379"
postgres:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: postgres
  volumes:
    - ./data/postgres:/var/lib/postgresql
mysql:
  image: mysql:5.6
  ports:
    - "3306:3306"
  volumes:
    - ./data/mysql:/docker-entrypoint-initdb.d
  environment:
    MYSQL_ROOT_PASSWORD: password